ARG NODE_VERSION=10.16
FROM node:${NODE_VERSION}-alpine

RUN apk add --no-cache \
        bash \
        curl \
        eudev-dev \
        g++ \
        gcc \
        git \
        libffi-dev \
        libstdc++ \
        libusb \
        libusb-dev \
        linux-headers \
        make \
        musl-dev \
        openssl-dev \
        python-dev \
        python3-dev \
        supervisor \
        tmux

VOLUME ["/augur"]

WORKDIR /augur

RUN yarn

